// +build ignore

// generated by stringer -type=tid; DO NOT EDIT

package bootstrap

import "fmt"

const (
	_tid_name_0 = "invalideof"
	_tid_name_1 = "eol"
	_tid_name_2 = "exclamation"
	_tid_name_3 = "ampersand"
	_tid_name_4 = "lparenrparenstarplus"
	_tid_name_5 = "dotslash"
	_tid_name_6 = "colonsemicolon"
	_tid_name_7 = "question"
	_tid_name_8 = "identruledefcharstrrstrclasslcommentmlcommentcode"
)

var (
	_tid_index_0 = [...]uint8{0, 7, 10}
	_tid_index_1 = [...]uint8{0, 3}
	_tid_index_2 = [...]uint8{0, 11}
	_tid_index_3 = [...]uint8{0, 9}
	_tid_index_4 = [...]uint8{0, 6, 12, 16, 20}
	_tid_index_5 = [...]uint8{0, 3, 8}
	_tid_index_6 = [...]uint8{0, 5, 14}
	_tid_index_7 = [...]uint8{0, 8}
	_tid_index_8 = [...]uint8{0, 5, 12, 16, 19, 23, 28, 36, 45, 49}
)

func (i tid) String() string {
	switch {
	case -1 <= i && i <= 0:
		i -= -1
		return _tid_name_0[_tid_index_0[i]:_tid_index_0[i+1]]
	case i == 10:
		return _tid_name_1
	case i == 33:
		return _tid_name_2
	case i == 38:
		return _tid_name_3
	case 40 <= i && i <= 43:
		i -= 40
		return _tid_name_4[_tid_index_4[i]:_tid_index_4[i+1]]
	case 46 <= i && i <= 47:
		i -= 46
		return _tid_name_5[_tid_index_5[i]:_tid_index_5[i+1]]
	case 58 <= i && i <= 59:
		i -= 58
		return _tid_name_6[_tid_index_6[i]:_tid_index_6[i+1]]
	case i == 63:
		return _tid_name_7
	case 129 <= i && i <= 137:
		i -= 129
		return _tid_name_8[_tid_index_8[i]:_tid_index_8[i+1]]
	default:
		return fmt.Sprintf("tid(%d)", i)
	}
}
