FROM        golang:1.6-alpine

# TODO : update once moved to final repository
ENV         DIR /go/src/github.com/PuerkitoBio/exp/juggler

# Copy the app in its correct path in the container.
RUN         mkdir -p $DIR
WORKDIR     $DIR
COPY        . $DIR

# Build the client
RUN         go build ./cmd/juggler-client/
CMD         ["./juggler-client", "--addr", "ws://docker_server_1:9000/ws"]

